services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: "1000:1000"
    volumes:
      - .:/app
    depends_on:
      - database
      - database_test
    networks:
      - app-network
    environment:
      DATABASE_URL: "pgsql://app:SecurePass123!@database:5432/products"
      DATABASE_TEST_URL: "pgsql://app:SecurePass123!@database_test:5432/products_test"

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_PASSWORD: SecurePass123!
      POSTGRES_USER: app
    ports:
      - "57036:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network

  database_test:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: products_test
      POSTGRES_PASSWORD: SecurePass123!
      POSTGRES_USER: app
    ports:
      - "57037:5432"
    networks:
      - app-network

volumes:
  database_data:

networks:
  app-network:
    driver: bridge